framework: jest
postMerge:
  pattern: 
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preMerge:
  pattern:
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - npm --version
version: 2.0
